name: Python application

on:
  workflow_dispatch:
    inputs:
      parameter_name:
        description: 'Description of the parameter'
        required: false

# on:
#   schedule:
#     - cron: '18 13 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build docker image
      run: docker build --build-arg USERNAME=${{ vars.USERNAME }} --build-arg PASSWORD="${{ secrets.PASSWORD }}" -t bot:latest .

    - name: Run docker image
      run: docker run --name bot bot:latest && docker ps
