# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  schedule:
    - cron: '18 13 * * *'
    
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Check if secret is accessable
      run: |
        if [ $PASSWORD ]
        then
          echo "Secret available"
        else
          echo "Secret not available"
          exit 1
        fi
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install instabot
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run code
      run: |
        python bot.py
